#pragma once

#define RGBLIGHT_SLEEP
#define RGBLIGHT_DEFAULT_VAL 0

#define TAPPING_TERM 300
#define IGNORE_MOD_TAP_INTERRUPT

#ifdef DYNAMIC_KEYMAP_LAYER_COUNT
    #undef DYNAMIC_KEYMAP_LAYER_COUNT
#endif
#define DYNAMIC_KEYMAP_LAYER_COUNT 8

#undef  COCOT_SCROLL_INV_DEFAULT
#define COCOT_SCROLL_INV_DEFAULT -1

#undef  COCOT_CPI_DEFAULT
#define COCOT_CPI_DEFAULT 2

#undef  COCOT_ROTATION_DEFAULT
#define COCOT_ROTATION_DEFAULT 4
