#pragma once

#define RGBLIGHT_SLEEP

#define TAPPING_TERM 300
#define IGNORE_MOD_TAP_INTERRUPT

#ifdef DYNAMIC_KEYMAP_LAYER_COUNT
    #undef DYNAMIC_KEYMAP_LAYER_COUNT
#endif
#define DYNAMIC_KEYMAP_LAYER_COUNT 8
